### ISSUE TITLE
Problem running the demo

### ISSUE THREAD

**Issue by APX403** [ElectronNET/electron.net-api-demos#25] opened 2021-03-28 15:04 UTC
The demo is launching but all button "View Demo" does nothing. I don't see any error in the console of dev tools. 

Am I missing something ?

https://i.ibb.co/z84Xmn5/electronnetdemobug.gif

Thanks

**Comment by zhaobinbin2019** [comment] 2021-04-15 02:54
same issue with me. 
node version v14.16.0
.net core version 3.1
ElectronNET-API version 8.31.2
it looks like the IPC function not work?

**Comment by scharli** [comment] 2021-04-23 21:20
Same here, the buttons did not work on mac

**Comment by alifhaikal88** [comment] 2021-04-30 20:54
> Same here, the buttons did not work on mac

same issue

**Comment by craigfarrell** [comment] 2021-05-02 13:53
Is anyone looking at this?  None of the buttons do anything...

**Comment by johguentner** [comment] 2021-05-11 08:56
> Is anyone looking at this? None of the buttons do anything...
@craigfarrell

same Problem here. I'm trying to find the cause, but until now I have not figured it out.

**Comment by nathenxbrewer** [comment] 2021-05-13 12:48
Same here. UI works but all the 'View Demo' buttons do not.

**Comment by DmitryBolotin** [comment] 2021-05-14 14:20
Hi guys. You can check this folder. It is pretty the same, but it works -> https://github.com/ElectronNET/Electron.NET/tree/master/ElectronNET.WebApp

**Comment by langyo** [comment] 2021-08-11 12:01
same issue

**Comment by alan0428a** [comment] 2021-09-13 07:26
same here

**Comment by AndreyBilalov** [comment] 2021-09-14 07:27
You need execute electronize start command before starting application.

**Comment by mehran-mousavi** [comment] 2022-06-04 18:43
> The demo is launching but all button "View Demo" does nothing. I don't see any error in the console of dev tools.
> 
> Am I missing something ?
> 
> https://i.ibb.co/z84Xmn5/electronnetdemobug.gif
> 
> Thanks

Clone https://github.com/mehran-mousavi/electron.net-api-demos & Enjoy
Cheers!

**Comment by rattledoge** [comment] 2022-06-22 13:40
> Still having start issues. Getting following error;
![Screenshot_1](https://user-images.githubusercontent.com/71441854/175040723-314b15e0-a1b9-426f-997a-ed8861775a92.png)
Running on W10 with .Net Core 6.0.3 SDK and Node.js 18.4

**Comment by mehran-mousavi** [comment] 2022-06-24 05:36
> > Clone https://github.com/mehran-mousavi/electron.net-api-demos & Enjoy
> > Cheers!
> 
> Still having start issues. Getting following error; ![Screenshot_1](https://user-images.githubusercontent.com/71441854/175040723-314b15e0-a1b9-426f-997a-ed8861775a92.png) Running on W10 with .Net Core 6.0.3 SDK and Node.js 18.4
> 
> @mehran-mousavi

Hey, some improvements and fixes have been done. You may now clone the most recent stable .Net6 demo at:

https://github.com/mehran-mousavi/Electron.net-.Net-6-Demos

**Comment by GregorBiswanger** [comment] 2023-04-05 18:25
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Closed by GregorBiswanger** 2023-04-05 18:25 UTC
